# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push Image
      run: |
        az acr login --name containerregistryanna1111 --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} &&
        docker build -t containerregistryanna1111.azurecr.io/microhackapp:1 -f Dockerfile . &&
        docker push containerregistryanna1111.azurecr.io/microhackapp:1
